import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ThemeProvider } from "@/components/theme-provider"
import './globals.css'
import Navbar from '@/components/Navbar'
import Sidebar from '@/components/sidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'FotoFolio',
  description: 'Generated by Umar Khan',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          <div className='flex'>
            <div className='lg:w-1/5 hidden lg:block'>
              <Sidebar />
            </div>
            <div className='w-full'>{children}</div>

          </div>

        </ThemeProvider>
      </body>
    </html>
  )
}
